gateways:
    duckdb:
        connection:
            type: duckdb
            database: sqlmesh_multi_engine_demo.db
    snowflake:
        connection:
            type: snowflake
            account: {{ env_var('SNOWFLAKE_ACCOUNT') }} # TODO: export your env_var
            user: {{ env_var('SNOWFLAKE_USER') }} # TODO: export your env_var
            password: {{ env_var('SNOWFLAKE_PASSWORD') }} # TODO: export your env_var
            database: {{ env_var('SNOWFLAKE_DATABASE') }} # TODO: export your env
            role: {{ env_var('SNOWFLAKE_ROLE') }} # TODO: export your env

model_defaults:
    dialect: "@IF(@gateway = 'duckdb', 'duckdb', 'snowflake')"

default_gateway: duckdb

plan:
  enable_preview: true

ui:
  format_on_save: false

